---
- name: Ansible playbook to dockerize and run YOLO e-commerce app with Vagrant
  hosts: localhost
  become: true

  vars:
    vagrant_project_dir: /opt/yolo-vagrant
    git_repo: "https://github.com/danielsimon254/wk6ip"

  tasks:
    - name: Ensure necessary packages are installed
      ansible.builtin.package:
        name:
          - git
          - vagrant
          - virtualbox
        state: present

    - name: Create Vagrant project directory
      ansible.builtin.file:
        path: "{{ vagrant_project_dir }}"
        state: directory
        mode: '0755'

    - name: Clone the GitHub repository
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ vagrant_project_dir }}"
        version: HEAD

    - name: Initialize and start Vagrant
      command: vagrant up
      args:
        chdir: "{{ vagrant_project_dir }}"

    - name: Run Docker Compose on the VM
      community.docker.docker_compose:
        project_src: "/vagrant"
        state: present
        build: false
        pull: true
      delegate_to: localhost

    - name: Verify application accessibility
      uri:
        url: "http://localhost:3000"
        status_code: 200
